services:
  gymone-web:
    build: .
    restart: always
    ports:
     
      - "100.87.51.69:8080:80" 
    volumes:
      - .:/var/www/html 
    networks:
      - gymone-internal
      - dokploy-network

  gymone-db:
    image: mariadb:10.11
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=cambia_esta_clave_maestra_root
      - MYSQL_DATABASE=gymone_prod
      - MYSQL_USER=gymone_admin
      - MYSQL_PASSWORD=cambia_este_password_seguro
    volumes:
      - ../files/gymone_db:/var/lib/mysql
    networks:
      - gymone-internal

networks:
  gymone-internal:
    driver: bridge
  dokploy-network:
    external: true
