YAML
version: '3.8'

services:
  gymone-web:
    build: .
    restart: always
    # Dokploy inyectará el código clonado directamente aquí
    volumes:
      - .:/var/www/html 
    networks:
      - gymone-internal
      - dokploy-network # Red obligatoria para que el proxy Traefik de Dokploy lo detecte

  gymone-db:
    image: mariadb:10.11
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=cambia_esta_clave_maestra_root
      - MYSQL_DATABASE=gymone_prod
      - MYSQL_USER=gymone_admin
      - MYSQL_PASSWORD=cambia_este_password_seguro
    volumes:
      # Usamos el directorio sugerido por Dokploy para persistencia local robusta
      - ../files/gymone_db:/var/lib/mysql
    networks:
      - gymone-internal

networks:
  gymone-internal:
    driver: bridge
  dokploy-network:
    external: true # Le dice a Docker que use la red nativa de Dokploy
